# Generated by Django 3.1 on 2022-07-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220708_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
